CREATE TABLE public.users(
	id INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
	email CHARACTER VARYING(320) NOT NULL,
	password CHARACTER VARYING(25) NOT NULL,
	CONSTRAINT pk_users PRIMARY KEY(id),
	CONSTRAINT uc_users_email UNIQUE(email)
);

CREATE TABLE public.employees(
	id INT NOT NULL,
 	first_name CHARACTER VARYING(35) NOT NULL,
	last_name CHARACTER VARYING(35) NOT NULL,
	CONSTRAINT pk_employees PRIMARY KEY(id),
	CONSTRAINT fk_employees_users FOREIGN KEY(id) REFERENCES public.users(id)
);

CREATE TABLE public.condidates(
	id INT NOT NULL,
 	first_name CHARACTER VARYING(35) NOT NULL,
	last_name CHARACTER VARYING(35) NOT NULL,
	identity_number CHARACTER VARYING(11) NOT NULL,
	birth_year INT NOT NULL,
	CONSTRAINT pk_condidates PRIMARY KEY(id),
	CONSTRAINT fk_condidates_users FOREIGN KEY(id) REFERENCES public.users(id),
	CONSTRAINT uc_condidates_identitiy_number UNIQUE(identity_number)
);

CREATE TABLE public.employers(
	id INT NOT NULL,
 	company_name CHARACTER VARYING(255) NOT NULL,
	web_adress CHARACTER VARYING(50) NOT NULL,
	phone_number CHARACTER VARYING(12) NOT NULL,
	CONSTRAINT pk_employers PRIMARY KEY(id),
	CONSTRAINT fk_employers_users FOREIGN KEY(id) REFERENCES public.users(id)
);

CREATE TABLE public.verification_codes(
	id INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
 	code CHARACTER VARYING(38) NOT NULL,
	is_verified BOOLEAN NOT NULL,
	verification_date DATE,
	CONSTRAINT pk_verification_codes PRIMARY KEY(id),
	CONSTRAINT uc_verification_codes_code UNIQUE(code)
);

CREATE TABLE public.verification_code_condidates(
	id INT NOT NULL,
 	condidate_id INT NOT NULL,
	CONSTRAINT pk_verification_code_condidates PRIMARY KEY(id),
	CONSTRAINT fk_verification_code_condidates_verification_codes
	FOREIGN KEY(id) REFERENCES public.verification_codes(id),
	CONSTRAINT fk_verification_code_condidates_condidates
	FOREIGN KEY(condidate_id) REFERENCES public.condidates(id)
);

CREATE TABLE public.verification_code_employers(
	id INT NOT NULL,
 	employer_id INT NOT NULL,
	CONSTRAINT pk_verification_code_employers PRIMARY KEY(id),
	CONSTRAINT fk_verification_code_employers_verification_codes
	FOREIGN KEY(id) REFERENCES public.verification_codes(id),
	CONSTRAINT fk_verification_code_employers_employers
	FOREIGN KEY(employer_id) REFERENCES public.employers(id)
);

CREATE TABLE public.employee_confirms(
	id INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
 	employee_id INT NOT NULL,
	is_confirmed BOOLEAN NOT NULL,
	confirm_date DATE,
	CONSTRAINT pk_employee_confirms PRIMARY KEY(id),
	CONSTRAINT fk_employee_confirms_employee_id
	FOREIGN KEY(employee_id) REFERENCES public.employers(id)
);

CREATE TABLE public.employee_confirm_employers(
	id INT NOT NULL,
 	employer_id INT NOT NULL,
	CONSTRAINT pk_employee_confirm_employers PRIMARY KEY(id),
	CONSTRAINT fk_employee_confirm_employers_employee_confirms
	FOREIGN KEY(id) REFERENCES public.employee_confirms(id),
	CONSTRAINT fk_employee_confirm_employers_employers
	FOREIGN KEY(employer_id) REFERENCES public.employers(id)
);

CREATE TABLE public.job_titles(
	id INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
 	title CHARACTER VARYING(255) NOT NULL,
	CONSTRAINT pk_job_titles PRIMARY KEY(id),
	CONSTRAINT uc_job_titles_title UNIQUE(title)
);

CREATE TABLE public.cities
(
    id INTEGER NOT NULL,
    city_name character varying(50) NOT NULL,
    CONSTRAINT pk_cities PRIMARY KEY (id)
);

CREATE TABLE public.job_advertisement
(
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employer_id INTEGER NOT NULL,
    job_titles_id INTEGER NOT NULL,
    city_id INTEGER NOT NULL,
    job_description character varying(500) NOT NULL,
    min_salary INTEGER,
    max_salary INTEGER,
    number_of_open_positions INTEGER NOT NULL,
    application_deadline character varying(50) NOT NULL,
    is_active boolean NOT NULL,
    creation_date character varying(50) NOT NULL,
    CONSTRAINT pk_job_advertisement PRIMARY KEY (id),
	CONSTRAINT fk_job_advertisement_employers FOREIGN KEY (employer_id) REFERENCES public.employers (id),
	CONSTRAINT fk_job_advertisement_job_titles FOREIGN KEY (job_titles_id) REFERENCES public.job_titles (id),
	CONSTRAINT fk_job_advertisement_cities FOREIGN KEY (city_id) REFERENCES public.cities (id)
);