-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.employers
(
    employers_id integer NOT NULL,
    company_name character varying(50) NOT NULL,
    website character varying(50) NOT NULL,
    eposta character varying(50) NOT NULL,
    telephone character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    PRIMARY KEY (employers_id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    position_name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seekers
(
    job_seekers_id integer NOT NULL,
    firstname character varying(50) NOT NULL,
    lastname character varying(50) NOT NULL,
    tckn character varying(11) NOT NULL,
    birthday date NOT NULL,
    eposta character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    PRIMARY KEY (job_seekers_id)
);

CREATE TABLE public.system_employees
(
    system_employee_id integer NOT NULL,
    firstname character varying(50) NOT NULL,
    lastname character varying(50) NOT NULL,
    department_id integer NOT NULL,
    PRIMARY KEY (system_employee_id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.employers
    ADD FOREIGN KEY (employers_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (job_seekers_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.system_employees
    ADD FOREIGN KEY (system_employee_id)
    REFERENCES public.users (id)
    NOT VALID;

END;